// Auto-generated TypeScript types for HMU-ATL Database Schema
// Generated by Schema Agent (Agent 01)

export type UserType = 'rider' | 'driver' | 'both';
export type BackgroundCheckStatus = 'pending' | 'approved' | 'rejected' | 'expired';
export type VehicleType = 'sedan' | 'suv' | 'van' | 'luxury' | 'xl';
export type InspectionStatus = 'pending' | 'approved' | 'rejected' | 'expired';
export type RideRequestStatus = 'pending' | 'matched' | 'accepted' | 'cancelled' | 'expired';
export type RideStatus = 'accepted' | 'driver_arrived' | 'in_progress' | 'completed' | 'cancelled';
export type PaymentStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
export type TransactionType = 'ride_payment' | 'refund' | 'payout' | 'deposit' | 'withdrawal' | 'fee' | 'tip' | 'adjustment';
export type TransactionStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled' | 'refunded';
export type PayoutStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
export type DisputeType = 'fare_dispute' | 'route_dispute' | 'behavior' | 'cleanliness' | 'item_lost' | 'safety_concern' | 'payment_issue' | 'cancellation_fee' | 'other';
export type DisputeStatus = 'open' | 'under_review' | 'resolved' | 'closed' | 'escalated';
export type Priority = 'low' | 'medium' | 'high' | 'urgent';
export type NotificationType = 'ride_request' | 'ride_accepted' | 'driver_arrived' | 'ride_started' | 'ride_completed' | 'payment_received' | 'payout_processed' | 'rating_received' | 'promotion' | 'system_alert' | 'dispute_update' | 'document_expiry' | 'other';
export type NotificationPriority = 'low' | 'normal' | 'high' | 'urgent';
export type DiscountType = 'percentage' | 'fixed_amount' | 'free_ride';
export type ApplicableUserType = 'rider' | 'driver' | 'both' | 'new_users';

export interface User {
  id: string;
  email: string;
  phone_number: string;
  full_name: string;
  user_type: UserType;
  auth_provider?: string;
  auth_provider_id?: string;
  profile_image_url?: string;
  is_verified: boolean;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
  last_login_at?: Date;
}

export interface DriverProfile {
  id: string;
  user_id: string;
  driver_license_number: string;
  license_state: string;
  license_expiry_date: Date;
  driver_license_image_url?: string;
  background_check_status: BackgroundCheckStatus;
  background_check_date?: Date;
  insurance_provider?: string;
  insurance_policy_number?: string;
  insurance_expiry_date?: Date;
  insurance_document_url?: string;
  is_online: boolean;
  current_latitude?: number;
  current_longitude?: number;
  last_location_update?: Date;
  total_rides_completed: number;
  total_earnings: number;
  average_rating: number;
  acceptance_rate: number;
  cancellation_rate: number;
  created_at: Date;
  updated_at: Date;
}

export interface RiderProfile {
  id: string;
  user_id: string;
  preferred_payment_method?: string;
  home_address_latitude?: number;
  home_address_longitude?: number;
  home_address_street?: string;
  work_address_latitude?: number;
  work_address_longitude?: number;
  work_address_street?: string;
  total_rides_taken: number;
  total_spent: number;
  average_rating: number;
  created_at: Date;
  updated_at: Date;
}

export interface VehicleInformation {
  id: string;
  driver_id: string;
  make: string;
  model: string;
  year: number;
  color: string;
  license_plate: string;
  vin: string;
  vehicle_type: VehicleType;
  seat_capacity: number;
  registration_state: string;
  registration_expiry_date: Date;
  registration_document_url?: string;
  inspection_status: InspectionStatus;
  inspection_date?: Date;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface RideRequest {
  id: string;
  rider_id: string;
  pickup_latitude: number;
  pickup_longitude: number;
  pickup_address: string;
  dropoff_latitude: number;
  dropoff_longitude: number;
  dropoff_address: string;
  estimated_distance_km?: number;
  estimated_duration_minutes?: number;
  estimated_fare?: number;
  vehicle_type_requested: VehicleType;
  seat_count_requested: number;
  status: RideRequestStatus;
  matched_driver_id?: string;
  created_at: Date;
  expires_at?: Date;
  cancelled_by?: string;
  cancellation_reason?: string;
}

export interface Ride {
  id: string;
  ride_request_id: string;
  rider_id: string;
  driver_id: string;
  vehicle_id?: string;
  pickup_latitude: number;
  pickup_longitude: number;
  pickup_address: string;
  dropoff_latitude: number;
  dropoff_longitude: number;
  dropoff_address: string;
  status: RideStatus;
  actual_distance_km?: number;
  actual_duration_minutes?: number;
  base_fare: number;
  distance_fare: number;
  time_fare: number;
  surge_multiplier: number;
  tip_amount: number;
  total_fare: number;
  driver_earnings?: number;
  platform_fee?: number;
  payment_status: PaymentStatus;
  started_at?: Date;
  driver_arrived_at?: Date;
  completed_at?: Date;
  cancelled_at?: Date;
  cancelled_by?: string;
  cancellation_reason?: string;
  created_at: Date;
}

export interface Transaction {
  id: string;
  user_id: string;
  ride_id?: string;
  transaction_type: TransactionType;
  amount: number;
  currency: string;
  payment_method?: string;
  payment_processor?: string;
  processor_transaction_id?: string;
  status: TransactionStatus;
  description?: string;
  metadata?: Record<string, any>;
  created_at: Date;
  processed_at?: Date;
}

export interface Payout {
  id: string;
  driver_id: string;
  amount: number;
  currency: string;
  payout_method: string;
  payout_account_id?: string;
  status: PayoutStatus;
  processor_payout_id?: string;
  period_start_date: Date;
  period_end_date: Date;
  rides_count: number;
  total_earnings?: number;
  platform_fees?: number;
  adjustments: number;
  net_payout?: number;
  scheduled_date?: Date;
  processed_at?: Date;
  failure_reason?: string;
  metadata?: Record<string, any>;
  created_at: Date;
}

export interface Dispute {
  id: string;
  ride_id: string;
  raised_by_user_id: string;
  dispute_type: DisputeType;
  status: DisputeStatus;
  priority: Priority;
  description: string;
  evidence_urls?: string[];
  admin_notes?: string;
  resolution?: string;
  resolved_by_admin_id?: string;
  resolved_at?: Date;
  refund_amount: number;
  created_at: Date;
  updated_at: Date;
}

export interface RatingAndReview {
  id: string;
  ride_id: string;
  rater_user_id: string;
  rated_user_id: string;
  rating: number;
  review_text?: string;
  categories?: Record<string, any>;
  is_flagged: boolean;
  flagged_reason?: string;
  created_at: Date;
}

export interface Notification {
  id: string;
  user_id: string;
  notification_type: NotificationType;
  title: string;
  message: string;
  priority: NotificationPriority;
  is_read: boolean;
  read_at?: Date;
  related_entity_type?: string;
  related_entity_id?: string;
  action_url?: string;
  metadata?: Record<string, any>;
  created_at: Date;
}

export interface EngagementMetric {
  id: string;
  user_id: string;
  metric_date: Date;
  rides_as_driver: number;
  rides_as_rider: number;
  total_distance_driven_km: number;
  total_time_online_minutes: number;
  earnings_as_driver: number;
  spending_as_rider: number;
  app_opens: number;
  session_duration_minutes: number;
  push_notifications_sent: number;
  push_notifications_opened: number;
  promotions_used: number;
  referrals_made: number;
  created_at: Date;
}

export interface SurgePricingZone {
  id: string;
  zone_name: string;
  zone_polygon: Record<string, any>;
  surge_multiplier: number;
  is_active: boolean;
  start_time: Date;
  end_time?: Date;
  reason?: string;
  created_at: Date;
  updated_at: Date;
}

export interface PromoCode {
  id: string;
  code: string;
  description?: string;
  discount_type: DiscountType;
  discount_value: number;
  max_discount_amount?: number;
  min_ride_amount?: number;
  usage_limit?: number;
  usage_count: number;
  valid_from: Date;
  valid_until: Date;
  applicable_user_type?: ApplicableUserType;
  is_active: boolean;
  created_at: Date;
}

// Database schema metadata
export const SCHEMA_VERSION = '1.0.0';
export const SCHEMA_CREATED_AT = new Date().toISOString();
