// Static inventory of every admin destination available to the search palette.
// Each entry pairs a route with the permission slug needed to *view* it (must
// match the sidebar's gating in `app/admin/components/admin-sidebar.tsx`) and
// a list of keywords/synonyms used by the fuzzy matcher.
//
// Adding a new admin page: append an entry here so it shows up in search.
// Items without a `permission` are visible to every admin (matches sidebar).

export interface AdminSearchItem {
  id: string;
  label: string;
  // Short description of what an admin does on this screen. Renders inline
  // next to the label in the search dropdown. Keep to ≤60 chars; favor a
  // verb-led primary action ("Monitor live activity", "Send SMS blasts").
  description: string;
  href: string;
  section: 'Monitor' | 'Act' | 'Grow' | 'Raise' | 'System' | 'Tools';
  icon: string;
  // Sidebar permission slug — server checks `hasPermission(permission + '.view')`.
  // Omit for routes that should be visible to all admins.
  permission?: string;
  // Synonyms / common phrasings. The fuzzy matcher weights label highest, then
  // these. Keep them short and Atlanta-team-vocab where it matters.
  keywords: string[];
}

export const ADMIN_SEARCH_MANIFEST: AdminSearchItem[] = [
  // ── MONITOR ─────────────────────────────────────────────────────────
  {
    id: 'live-ops',
    label: 'Live Ops',
    description: 'Monitor real-time platform activity',
    href: '/admin',
    section: 'Monitor',
    icon: '⚡',
    keywords: ['dashboard', 'home', 'realtime', 'overview', 'now', 'today'],
  },
  {
    id: 'growth',
    label: 'Growth',
    description: 'Track signups, targets, and area coverage',
    href: '/admin/growth',
    section: 'Monitor',
    icon: '📈',
    permission: 'monitor.liveops',
    keywords: ['signups', 'charts', 'targets', 'area coverage', 'metrics'],
  },
  {
    id: 'revenue',
    label: 'Revenue',
    description: 'Review earnings, payouts, and platform fees',
    href: '/admin/money',
    section: 'Monitor',
    icon: '💰',
    permission: 'monitor.revenue',
    keywords: ['money', 'payouts', 'fees', 'earnings', 'transactions', 'finance'],
  },
  {
    id: 'pricing',
    label: 'Pricing',
    description: 'Tune fee tiers and platform caps',
    href: '/admin/pricing',
    section: 'Monitor',
    icon: '⚙️',
    permission: 'monitor.pricing',
    keywords: ['rates', 'tiers', 'fees', 'platform fee', 'caps'],
  },
  {
    id: 'schedule',
    label: 'Schedules',
    description: 'View driver availability and coverage gaps',
    href: '/admin/schedule',
    section: 'Monitor',
    icon: '📅',
    permission: 'monitor.schedules',
    keywords: ['calendar', 'driver schedule', 'availability'],
  },

  // ── ACT ─────────────────────────────────────────────────────────────
  {
    id: 'support',
    label: 'Support',
    description: 'Triage support tickets and replies',
    href: '/admin/support',
    section: 'Act',
    icon: '🎫',
    permission: 'act.support',
    keywords: ['tickets', 'help', 'inbox', 'cs'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'Send push and broadcast alerts',
    href: '/admin/notifications',
    section: 'Act',
    icon: '🔔',
    permission: 'act.notifications',
    keywords: ['push', 'broadcast', 'alerts'],
  },
  {
    id: 'disputes',
    label: 'Disputes',
    description: 'Resolve ride disputes and refunds',
    href: '/admin/disputes',
    section: 'Act',
    icon: '⚖️',
    permission: 'act.disputes',
    keywords: ['refunds', 'complaints', 'nah fam', 'queue'],
  },
  {
    id: 'safety',
    label: 'Safety',
    description: 'Review safety incidents and check-ins',
    href: '/admin/safety',
    section: 'Act',
    icon: '🛡️',
    keywords: ['weirdo', 'incidents', 'check-ins', 'distress'],
  },
  {
    id: 'users',
    label: 'Users',
    description: 'Manage rider and driver accounts',
    href: '/admin/users',
    section: 'Act',
    icon: '👥',
    permission: 'act.users',
    keywords: ['riders', 'drivers', 'accounts', 'profiles', 'people'],
  },
  {
    id: 'ride-requests',
    label: 'Ride Requests',
    description: 'Inspect pending and active ride posts',
    href: '/admin/ride-requests',
    section: 'Act',
    icon: '🚖',
    keywords: ['rides', 'requests', 'pending'],
  },
  {
    id: 'hmus',
    label: 'HMUs',
    description: 'Audit driver-to-rider HMU links',
    href: '/admin/hmus',
    section: 'Act',
    icon: '📣',
    keywords: ['driver to rider', 'link', 'hmu link', 'directed interest'],
  },
  {
    id: 'suspect-usage',
    label: 'Suspect Usage',
    description: 'Investigate flagged accounts and abuse',
    href: '/admin/suspect-usage',
    section: 'Act',
    icon: '🚨',
    permission: 'act.suspect',
    keywords: ['fraud', 'abuse', 'flags', 'anomaly'],
  },

  // ── GROW ────────────────────────────────────────────────────────────
  {
    id: 'activation',
    label: 'Activation',
    description: 'Nurture payment-ready drivers and riders to first match',
    href: '/admin/activation',
    section: 'Grow',
    icon: '🚀',
    keywords: ['activation', 'nurture', 'payment ready', 'completeness', 'coverage', 'areas', 'nudge'],
  },
  {
    id: 'outreach',
    label: 'Outreach',
    description: 'Send SMS blasts and manage campaigns',
    href: '/admin/marketing',
    section: 'Grow',
    icon: '📣',
    permission: 'grow.outreach',
    keywords: ['marketing', 'sms', 'blast', 'campaign', 'csv', 'thread'],
  },
  {
    id: 'messages',
    label: 'Messages',
    description: 'Reply to inbound SMS threads',
    href: '/admin/messages',
    section: 'Grow',
    icon: '💬',
    permission: 'grow.messages',
    keywords: ['sms inbox', 'threads', 'conversations', 'replies'],
  },
  {
    id: 'playbook',
    label: 'Playbook',
    description: 'Curate canned answers admins send from /admin/messages',
    href: '/admin/playbook',
    section: 'Grow',
    icon: '📚',
    permission: 'grow.playbook',
    keywords: ['canned', 'macros', 'templates', 'faq', 'snippets', 'replies', 'q&a'],
  },
  {
    id: 'leads',
    label: 'Leads',
    description: 'Work the homepage email waitlist',
    href: '/admin/leads',
    section: 'Grow',
    icon: '📧',
    permission: 'grow.leads',
    keywords: ['homepage leads', 'email signups', 'waitlist'],
  },
  {
    id: 'content',
    label: 'Content',
    description: 'Manage social videos and creative',
    href: '/admin/content',
    section: 'Grow',
    icon: '🎬',
    permission: 'grow.content',
    keywords: ['videos', 'social', 'ads', 'creative'],
  },
  {
    id: 'funnel',
    label: 'Funnel CMS',
    description: 'Edit landing page copy by zone',
    href: '/admin/funnel',
    section: 'Grow',
    icon: '📝',
    permission: 'grow.funnel',
    keywords: ['copy', 'pages', 'cms', 'zones', 'landing'],
  },
  {
    id: 'driver-playbook',
    label: 'Playbook FB Groups',
    description: 'Track Facebook driver-recruit groups',
    href: '/admin/driver-playbook/fb-groups',
    section: 'Grow',
    icon: '👥',
    keywords: ['facebook', 'groups', 'playbook', 'driver recruit'],
  },
  {
    id: 'conversation-agent',
    label: 'Conversation Agent',
    description: 'Configure the AI auto-reply agent',
    href: '/admin/conversation-agent',
    section: 'Grow',
    icon: '💬',
    keywords: ['ai', 'auto reply', 'gpt', 'agent'],
  },
  {
    id: 'chat-booking',
    label: 'Chat Booking',
    description: 'Configure SMS-driven booking flow',
    href: '/admin/chat-booking',
    section: 'Grow',
    icon: '🤖',
    keywords: ['sms booking', 'inbound book', 'auto book'],
  },

  // ── RAISE ───────────────────────────────────────────────────────────
  {
    id: 'data-room',
    label: 'Data Room',
    description: 'Share investor metrics and docs',
    href: '/admin/data-room',
    section: 'Raise',
    icon: '🔒',
    permission: 'raise.dataroom',
    keywords: ['investors', 'metrics', 'fundraise'],
  },
  {
    id: 'pitch-videos',
    label: 'Pitch Videos',
    description: 'Manage investor pitch videos',
    href: '/admin/pitch-videos',
    section: 'Raise',
    icon: '📱',
    permission: 'raise.pitch',
    keywords: ['investor video', 'pitch deck'],
  },
  {
    id: 'videos',
    label: 'Videos',
    description: 'Render Remotion feature videos',
    href: '/admin/videos',
    section: 'Raise',
    icon: '🎥',
    permission: 'raise.videos',
    keywords: ['remotion', 'feature videos', 'documentation'],
  },
  {
    id: 'docs',
    label: 'Tech Docs',
    description: 'Browse architecture and tech docs',
    href: '/admin/docs',
    section: 'Raise',
    icon: '📄',
    permission: 'raise.docs',
    keywords: ['documentation', 'architecture', 'whitepaper'],
  },

  // ── SYSTEM ──────────────────────────────────────────────────────────
  {
    id: 'roles',
    label: 'Roles',
    description: 'Manage admin roles and permissions',
    href: '/admin/roles',
    section: 'System',
    icon: '🔑',
    permission: 'admin.roles',
    keywords: ['rbac', 'permissions', 'access', 'admin users'],
  },
  {
    id: 'markets',
    label: 'Markets',
    description: 'Configure cities and expansion markets',
    href: '/admin/markets',
    section: 'System',
    icon: '🌎',
    keywords: ['atl', 'nola', 'cities', 'regions', 'expansion'],
  },
  {
    id: 'feature-flags',
    label: 'Feature Flags',
    description: 'Toggle experiments and gated features',
    href: '/admin/feature-flags',
    section: 'System',
    icon: '🚩',
    keywords: ['flags', 'toggles', 'experiments', 'gates'],
  },
  {
    id: 'hmu-config',
    label: 'HMU Config',
    description: 'Tune HMU link caps and behavior',
    href: '/admin/hmu-config',
    section: 'System',
    icon: '📣',
    keywords: ['driver to rider', 'cap', 'hmu link cap'],
  },
  {
    id: 'onboarding-config',
    label: 'Onboarding Config',
    description: 'Set required driver signup fields',
    href: '/admin/onboarding-config',
    section: 'System',
    icon: '🛂',
    keywords: ['express signup', 'driver onboarding', 'fields', 'required'],
  },
  {
    id: 'realtime-banners',
    label: 'Realtime Banners',
    description: 'Configure live admin alert banners',
    href: '/admin/realtime-notifications',
    section: 'System',
    icon: '⚡',
    keywords: ['signup banner', 'super admin alert', 'live notification'],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    description: 'Run cleanup jobs and backfills',
    href: '/admin/maintenance',
    section: 'System',
    icon: '🚧',
    keywords: ['cleanup', 'backfill', 'scripts', 'jobs'],
  },
  {
    id: 'voip-debug',
    label: 'VoIP Debug',
    description: 'Inspect voip.ms SMS and DID activity',
    href: '/admin/voip-debug',
    section: 'System',
    icon: '📡',
    keywords: ['voip.ms', 'sms debug', 'phone numbers', 'did'],
  },
  {
    id: 'audit-log',
    label: 'Audit Log',
    description: 'See who did what in the admin portal',
    href: '/admin/audit',
    section: 'System',
    icon: '📋',
    permission: 'admin.audit',
    keywords: ['history', 'who did what', 'admin actions', 'changes'],
  },

  // ── TOOLS ───────────────────────────────────────────────────────────
  {
    id: 'flows',
    label: 'Flows',
    description: 'Read-only walkthroughs of user-facing onboarding flows',
    href: '/admin/flows',
    section: 'Tools',
    icon: '🧭',
    permission: 'tools.flows',
    keywords: ['onboarding preview', 'training', 'walkthrough', 'flows', 'simulator', 'demo'],
  },
  {
    id: 'flows-driver-express',
    label: 'Driver — Express Flow',
    description: 'Live preview of /driver/express signup',
    href: '/admin/flows/driver-express',
    section: 'Tools',
    icon: '🚗',
    permission: 'tools.flows',
    keywords: ['express driver', 'driver onboarding preview', 'training driver'],
  },
  {
    id: 'flows-rider-ad-funnel',
    label: 'Rider — /r/express Ad Funnel',
    description: 'Paid-ads conversion: handle → media → location → safety → payment',
    href: '/admin/flows/rider-ad-funnel',
    section: 'Tools',
    icon: '📣',
    permission: 'tools.flows',
    keywords: ['ad funnel rider', 'r/express', 'rider conversion', 'meta ads rider', 'tiktok ads rider', 'paid signup'],
  },
  {
    id: 'flows-rider',
    label: 'Rider — Standard /onboarding',
    description: 'Organic /sign-up rider path with FirstTimePaymentBlocker',
    href: '/admin/flows/rider',
    section: 'Tools',
    icon: '🙋',
    permission: 'tools.flows',
    keywords: ['rider onboarding preview', 'first time payment', 'rider signup', 'training rider', 'card link', 'organic signup'],
  },
  {
    id: 'flows-rider-express',
    label: 'Rider — Chat Booking Flow',
    description: 'Legacy minimal-fields rider signup from /d/{handle}',
    href: '/admin/flows/rider-express',
    section: 'Tools',
    icon: '💬',
    permission: 'tools.flows',
    keywords: ['express rider', 'chat booking signup', 'rider from share link'],
  },
];
