// Static inventory of every admin destination available to the search palette.
// Each entry is presentation only — label, description, icon, section, and
// fuzzy-match keywords. The permission rule that gates visibility lives in
// `lib/admin/route-permissions.ts`, keyed by `href`. The search API
// (`app/api/admin/search/route.ts`) calls `canAccessRoute(admin, href)` so
// search visibility tracks the layout guard and sidebar exactly.
//
// Adding a new admin page: register the route + rule in `route-permissions.ts`
// first, then append an entry here so it surfaces in search.

export interface AdminSearchItem {
  id: string;
  label: string;
  // Short description of what an admin does on this screen. Renders inline
  // next to the label in the search dropdown. Keep to ≤60 chars; favor a
  // verb-led primary action ("Monitor live activity", "Send SMS blasts").
  description: string;
  href: string;
  section: 'Monitor' | 'Act' | 'Grow' | 'Raise' | 'System' | 'Tools';
  icon: string;
  // Synonyms / common phrasings. The fuzzy matcher weights label highest, then
  // these. Keep them short and Atlanta-team-vocab where it matters.
  keywords: string[];
}

export const ADMIN_SEARCH_MANIFEST: AdminSearchItem[] = [
  // ── MONITOR ─────────────────────────────────────────────────────────
  {
    id: 'live-ops',
    label: 'Live Ops',
    description: 'Monitor real-time platform activity',
    href: '/admin',
    section: 'Monitor',
    icon: '⚡',
    keywords: ['dashboard', 'home', 'realtime', 'overview', 'now', 'today'],
  },
  {
    id: 'blast',
    label: 'Blast Monitor',
    description: 'Watch live blast bookings fan out to drivers',
    href: '/admin/blast',
    section: 'Monitor',
    icon: '📡',
    keywords: ['blast', 'broadcast', 'fanout', 'offers', 'blast booking', 'driver fanout', 'live blast', 'requests'],
  },
  {
    id: 'dashboards',
    label: 'Dashboards',
    description: 'Open custom user-grid dashboards and reports',
    href: '/admin/dashboards',
    section: 'Monitor',
    icon: '📊',
    keywords: ['custom dashboard', 'reports', 'user grid', 'data view', 'saved view', 'grids', 'analytics'],
  },
  {
    id: 'growth',
    label: 'Growth',
    description: 'Track signups, targets, and area coverage',
    href: '/admin/growth',
    section: 'Monitor',
    icon: '📈',
    keywords: ['signups', 'charts', 'targets', 'area coverage', 'metrics'],
  },
  {
    id: 'revenue',
    label: 'Revenue',
    description: 'Review earnings, payouts, and platform fees',
    href: '/admin/money',
    section: 'Monitor',
    icon: '💰',
    keywords: ['money', 'payouts', 'fees', 'earnings', 'transactions', 'finance', 'ledger', 'gmv', 'revenue', 'export', 'csv', 'refunds', 'stripe fees', '1099'],
  },
  {
    id: 'pricing',
    label: 'Pricing',
    description: 'Tune fee tiers and platform caps',
    href: '/admin/pricing',
    section: 'Monitor',
    icon: '⚙️',
    keywords: ['rates', 'tiers', 'fees', 'platform fee', 'caps'],
  },
  {
    id: 'schedule',
    label: 'Schedules',
    description: 'View driver availability and coverage gaps',
    href: '/admin/schedule',
    section: 'Monitor',
    icon: '📅',
    keywords: ['calendar', 'driver schedule', 'availability'],
  },

  // ── ACT ─────────────────────────────────────────────────────────────
  {
    id: 'support',
    label: 'Support',
    description: 'Triage support tickets and replies',
    href: '/admin/support',
    section: 'Act',
    icon: '🎫',
    keywords: ['tickets', 'help', 'inbox', 'cs'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'Send push and broadcast alerts',
    href: '/admin/notifications',
    section: 'Act',
    icon: '🔔',
    keywords: ['push', 'broadcast', 'alerts'],
  },
  {
    id: 'disputes',
    label: 'Disputes',
    description: 'Resolve ride disputes and refunds',
    href: '/admin/disputes',
    section: 'Act',
    icon: '⚖️',
    keywords: ['refunds', 'complaints', 'nah fam', 'queue'],
  },
  {
    id: 'safety',
    label: 'Safety',
    description: 'Review safety incidents and check-ins',
    href: '/admin/safety',
    section: 'Act',
    icon: '🛡️',
    keywords: ['weirdo', 'incidents', 'check-ins', 'distress'],
  },
  {
    id: 'users',
    label: 'Users',
    description: 'Manage rider and driver accounts',
    href: '/admin/users',
    section: 'Act',
    icon: '👥',
    keywords: ['riders', 'drivers', 'accounts', 'profiles', 'people', 'ban', 'suspend', 'unban', 'block', 'verify', 'kyc', 'tier', 'og status', 'find user', 'lookup'],
  },
  {
    id: 'ride-requests',
    label: 'Ride Requests',
    description: 'Inspect pending and active ride posts',
    href: '/admin/ride-requests',
    section: 'Act',
    icon: '🚖',
    keywords: ['rides', 'requests', 'pending'],
  },
  {
    id: 'hmus',
    label: 'HMUs',
    description: 'Audit driver-to-rider HMU links',
    href: '/admin/hmus',
    section: 'Act',
    icon: '📣',
    keywords: ['driver to rider', 'link', 'hmu link', 'directed interest'],
  },
  {
    id: 'suspect-usage',
    label: 'Suspect Usage',
    description: 'Investigate flagged accounts and abuse',
    href: '/admin/suspect-usage',
    section: 'Act',
    icon: '🚨',
    keywords: ['fraud', 'abuse', 'flags', 'anomaly', 'suspicious', 'self deal', 'collusion'],
  },
  {
    id: 'engage',
    label: 'Engage Console',
    description: 'Text riders who requested + drivers who missed',
    href: '/admin/engage',
    section: 'Act',
    icon: '📞',
    keywords: ['engage', 'outreach', 'text rider', 'missed', 'follow up', 'reactivate', 'win back', 'requested', 'no driver'],
  },
  {
    id: 'comments',
    label: 'Comment Moderation',
    description: 'Review GPT-flagged comments and profiles',
    href: '/admin/comments',
    section: 'Act',
    icon: '🗨️',
    keywords: ['moderation', 'comments', 'flagged', 'sentiment', 'report', 'abuse', 'hide', 'profanity', 'content moderation'],
  },

  // ── GROW ────────────────────────────────────────────────────────────
  {
    id: 'coverage',
    label: 'Coverage Map',
    description: 'See driver supply and demand gaps by area',
    href: '/admin/coverage',
    section: 'Grow',
    icon: '🗺️',
    keywords: ['coverage', 'map', 'supply', 'demand', 'gaps', 'areas', 'neighborhoods', 'heatmap', 'driver density'],
  },
  {
    id: 'activation',
    label: 'Activation',
    description: 'Nurture payment-ready drivers and riders to first match',
    href: '/admin/activation',
    section: 'Grow',
    icon: '🚀',
    keywords: ['activation', 'nurture', 'payment ready', 'completeness', 'coverage', 'areas', 'nudge'],
  },
  {
    id: 'outreach',
    label: 'Outreach',
    description: 'Send SMS blasts and manage campaigns',
    href: '/admin/marketing',
    section: 'Grow',
    icon: '📣',
    keywords: ['marketing', 'sms', 'blast', 'campaign', 'csv', 'thread'],
  },
  {
    id: 'messages',
    label: 'Messages',
    description: 'Reply to inbound SMS threads',
    href: '/admin/messages',
    section: 'Grow',
    icon: '💬',
    keywords: ['sms inbox', 'threads', 'conversations', 'replies'],
  },
  {
    id: 'playbook',
    label: 'Playbook',
    description: 'Curate canned answers admins send from /admin/messages',
    href: '/admin/playbook',
    section: 'Grow',
    icon: '📚',
    keywords: ['canned', 'macros', 'templates', 'faq', 'snippets', 'replies', 'q&a'],
  },
  {
    id: 'leads',
    label: 'Leads',
    description: 'Work the homepage email waitlist',
    href: '/admin/leads',
    section: 'Grow',
    icon: '📧',
    keywords: ['homepage leads', 'email signups', 'waitlist'],
  },
  {
    id: 'events',
    label: 'Event Inquiries',
    description: 'Triage venue + organizer partnership requests',
    href: '/admin/events',
    section: 'Grow',
    icon: '🎟️',
    keywords: ['events', 'venues', 'partnerships', 'promoters', 'flat rate'],
  },
  {
    id: 'content',
    label: 'Content',
    description: 'Manage social videos and creative',
    href: '/admin/content',
    section: 'Grow',
    icon: '🎬',
    keywords: ['videos', 'social', 'ads', 'creative'],
  },
  {
    id: 'funnel',
    label: 'Funnel CMS',
    description: 'Edit landing page copy by zone',
    href: '/admin/funnel',
    section: 'Grow',
    icon: '📝',
    keywords: ['copy', 'pages', 'cms', 'zones', 'landing'],
  },
  {
    id: 'driver-playbook',
    label: 'Playbook FB Groups',
    description: 'Track Facebook driver-recruit groups',
    href: '/admin/driver-playbook/fb-groups',
    section: 'Grow',
    icon: '👥',
    keywords: ['facebook', 'groups', 'playbook', 'driver recruit'],
  },
  {
    id: 'conversation-agent',
    label: 'Conversation Agent',
    description: 'Configure the AI auto-reply agent',
    href: '/admin/conversation-agent',
    section: 'Grow',
    icon: '💬',
    keywords: ['ai', 'auto reply', 'gpt', 'agent'],
  },
  {
    id: 'chat-booking',
    label: 'Chat Booking',
    description: 'Configure SMS-driven booking flow',
    href: '/admin/chat-booking',
    section: 'Grow',
    icon: '🤖',
    keywords: ['sms booking', 'inbound book', 'auto book'],
  },

  // ── RAISE ───────────────────────────────────────────────────────────
  {
    id: 'data-room',
    label: 'Data Room',
    description: 'Share investor metrics and docs',
    href: '/admin/data-room',
    section: 'Raise',
    icon: '🔒',
    keywords: ['investors', 'metrics', 'fundraise'],
  },
  {
    id: 'pitch-videos',
    label: 'Pitch Videos',
    description: 'Manage how-it-works videos (drivers, riders, investors)',
    href: '/admin/pitch-videos',
    section: 'Raise',
    icon: '📱',
    keywords: ['investor video', 'pitch deck'],
  },
  {
    id: 'videos',
    label: 'Videos',
    description: 'Render Remotion feature videos',
    href: '/admin/videos',
    section: 'Raise',
    icon: '🎥',
    keywords: ['remotion', 'feature videos', 'documentation'],
  },
  {
    id: 'docs',
    label: 'Tech Docs',
    description: 'Browse architecture and tech docs',
    href: '/admin/docs',
    section: 'Raise',
    icon: '📄',
    keywords: ['documentation', 'architecture', 'whitepaper'],
  },

  // ── SYSTEM ──────────────────────────────────────────────────────────
  {
    id: 'roles',
    label: 'Roles',
    description: 'Manage admin roles and permissions',
    href: '/admin/roles',
    section: 'System',
    icon: '🔑',
    keywords: ['rbac', 'permissions', 'access', 'admin users'],
  },
  {
    id: 'markets',
    label: 'Markets',
    description: 'Configure cities and expansion markets',
    href: '/admin/markets',
    section: 'System',
    icon: '🌎',
    keywords: ['atl', 'nola', 'cities', 'regions', 'expansion'],
  },
  {
    id: 'feature-flags',
    label: 'Feature Flags',
    description: 'Toggle experiments and gated features',
    href: '/admin/feature-flags',
    section: 'System',
    icon: '🚩',
    keywords: ['flags', 'toggles', 'experiments', 'gates'],
  },
  {
    id: 'hmu-config',
    label: 'HMU Config',
    description: 'Tune HMU link caps and behavior',
    href: '/admin/hmu-config',
    section: 'System',
    icon: '📣',
    keywords: ['driver to rider', 'cap', 'hmu link cap'],
  },
  {
    id: 'direct-booking-config',
    label: 'Direct Booking Config',
    description: 'Configure direct booking rules and driver linking',
    href: '/admin/direct-booking-config',
    section: 'System',
    icon: '🔗',
    keywords: ['direct booking', 'driver link', 'booking config', 'hmu config'],
  },
  {
    id: 'payments-config',
    label: 'Payments Config',
    description: 'Tune deposit fees, add-on reserve, and per-market overrides',
    href: '/admin/payments',
    section: 'System',
    icon: '💳',
    keywords: ['deposit', 'fees', 'stripe', 'platform fee', 'reserve', 'payment math', 'deposit only', 'pricing config'],
  },
  {
    id: 'blast-config',
    label: 'Blast Config',
    description: 'Tune blast booking matching algorithm and limits',
    href: '/admin/blast-config',
    section: 'System',
    icon: '💥',
    keywords: ['blast', 'booking', 'matching', 'fanout', 'sms cap', 'blast booking'],
  },
  {
    id: 'onboarding-config',
    label: 'Onboarding Config',
    description: 'Set required driver signup fields',
    href: '/admin/onboarding-config',
    section: 'System',
    icon: '🛂',
    keywords: ['express signup', 'driver onboarding', 'fields', 'required'],
  },
  {
    id: 'realtime-banners',
    label: 'Realtime Banners',
    description: 'Configure live admin alert banners',
    href: '/admin/realtime-notifications',
    section: 'System',
    icon: '⚡',
    keywords: ['signup banner', 'super admin alert', 'live notification'],
  },
  {
    id: 'rider-browse-banner',
    label: 'Browse Banner',
    description: 'Edit the driver-recruit banner on /rider/browse',
    href: '/admin/rider-browse-banner',
    section: 'System',
    icon: '📣',
    keywords: ['browse banner', 'driver recruit', 'rider page banner', 'apply here', 'cta'],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    description: 'Run cleanup jobs and backfills',
    href: '/admin/maintenance',
    section: 'System',
    icon: '🚧',
    keywords: ['cleanup', 'backfill', 'scripts', 'jobs'],
  },
  {
    id: 'voip-debug',
    label: 'VoIP Debug',
    description: 'Inspect voip.ms SMS and DID activity',
    href: '/admin/voip-debug',
    section: 'System',
    icon: '📡',
    keywords: ['voip.ms', 'sms debug', 'phone numbers', 'did'],
  },
  {
    id: 'voip-config',
    label: 'VoIP Config',
    description: 'Map markets to voip.ms DIDs and SMS settings',
    href: '/admin/voip-config',
    section: 'System',
    icon: '🔧',
    keywords: ['voip.ms', 'did', 'phone number', 'sms config', 'sender number', 'market did'],
  },
  {
    id: 'system-health',
    label: 'System Health',
    description: 'Monitor Stripe, Ably, API errors, and dead-letter queue',
    href: '/admin/system-health',
    section: 'System',
    icon: '🩺',
    keywords: ['health', 'status', 'uptime', 'errors', 'webhooks', 'dead letter', 'stripe health', 'ably health', 'monitoring', 'incidents'],
  },
  {
    id: 'chill-config',
    label: 'Chill Score Config',
    description: 'Tune the chill-score reputation algorithm',
    href: '/admin/chill-config',
    section: 'System',
    icon: '😎',
    keywords: ['chill score', 'reputation', 'rating algorithm', 'score config', 'weights'],
  },
  {
    id: 'down-bad',
    label: 'Down Bad Config',
    description: 'Tune the down-bad discount rescue offer',
    href: '/admin/down-bad',
    section: 'System',
    icon: '😮‍💨',
    keywords: ['down bad', 'discount', 'rescue offer', 'price drop', 'desperate', 'incentive'],
  },
  {
    id: 'partner-fees',
    label: 'Partner Delivery Fees',
    description: 'Set the money split on partner deliveries',
    href: '/admin/partner-fees',
    section: 'System',
    icon: '💳',
    keywords: ['partner', 'delivery fees', 'fee split', 'vendor', 'payer mode', 'partner api'],
  },
  {
    id: 'partner-keys',
    label: 'Partner API Keys',
    description: 'Mint and revoke partner API credentials',
    href: '/admin/partner-keys',
    section: 'System',
    icon: '🔌',
    keywords: ['partner', 'api key', 'credentials', 'hmac', 'secret', 'integration', 'vendor key'],
  },
  {
    id: 'cold-start',
    label: 'Cold Start',
    description: 'Keep prod Neon compute warm (changes billing)',
    href: '/admin/cold-start',
    section: 'System',
    icon: '🔥',
    keywords: ['cold start', 'neon', 'compute', 'warm', 'database', 'suspend', 'billing'],
  },
  {
    id: 'sms-templates',
    label: 'SMS Templates',
    description: 'Edit transactional SMS bodies live, no deploy',
    href: '/admin/sms-templates',
    section: 'System',
    icon: '✉️',
    keywords: ['sms templates', 'message text', 'driver sms', 'rider sms', 'edit sms', 'transactional'],
  },
  {
    id: 'audit-log',
    label: 'Audit Log',
    description: 'See who did what in the admin portal',
    href: '/admin/audit',
    section: 'System',
    icon: '📋',
    keywords: ['history', 'who did what', 'admin actions', 'changes'],
  },

  // ── TOOLS ───────────────────────────────────────────────────────────
  {
    id: 'flows',
    label: 'Flows',
    description: 'Read-only walkthroughs of user-facing onboarding flows',
    href: '/admin/flows',
    section: 'Tools',
    icon: '🧭',
    keywords: ['onboarding preview', 'training', 'walkthrough', 'flows', 'simulator', 'demo'],
  },
  {
    id: 'flows-driver-express',
    label: 'Driver — Express Flow',
    description: 'Live preview of /driver/express signup',
    href: '/admin/flows/driver-express',
    section: 'Tools',
    icon: '🚗',
    keywords: ['express driver', 'driver onboarding preview', 'training driver'],
  },
  {
    id: 'flows-rider-ad-funnel',
    label: 'Rider — /r/express Ad Funnel',
    description: 'Paid-ads conversion: handle → media → location → safety → payment',
    href: '/admin/flows/rider-ad-funnel',
    section: 'Tools',
    icon: '📣',
    keywords: ['ad funnel rider', 'r/express', 'rider conversion', 'meta ads rider', 'tiktok ads rider', 'paid signup'],
  },
  {
    id: 'flows-rider',
    label: 'Rider — Standard /onboarding',
    description: 'Organic /sign-up rider path with FirstTimePaymentBlocker',
    href: '/admin/flows/rider',
    section: 'Tools',
    icon: '🙋',
    keywords: ['rider onboarding preview', 'first time payment', 'rider signup', 'training rider', 'card link', 'organic signup'],
  },
  {
    id: 'flows-rider-express',
    label: 'Rider — Chat Booking Flow',
    description: 'Legacy minimal-fields rider signup from /d/{handle}',
    href: '/admin/flows/rider-express',
    section: 'Tools',
    icon: '💬',
    keywords: ['express rider', 'chat booking signup', 'rider from share link'],
  },
];
