import { Composition } from "remotion";
import { RideFlow } from "./compositions/RideFlow";

// Static manifest generated by: npm run video -- preview/render
// The CLI fetches all configs from Neon and writes this file.
// If it doesn't exist yet, we fall back to hardcoded defaults.
let manifest: { id: string; props: Record<string, unknown>; duration: number }[] = [];
try {
  manifest = require("./compositions.json");
} catch {
  // First run — no manifest yet. Fallbacks below will be used.
}

// 9:16 vertical (1080x1920) at 30fps
const VERTICAL_WIDTH = 1080;
const VERTICAL_HEIGHT = 1920;
const FPS = 30;

const DEFAULT_PROPS = {
  title: "HMU VIDEO",
  steps: [
    { sec: 2, label: "STEP ONE", caption: "Description here.", effect: "slide-up-bounce" as const },
  ],
  recordingFile: "recording.mp4",
  introSec: 3,
  videoSec: 60,
  endSec: 5,
  titleCardDurationSec: 2,
  captionDurationSec: 5,
  endTagline: "Your city. Your ride. Your rules.",
  endCta: "HMU ATL",
  phoneWidth: 480,
  phoneHeight: 1036,
  muted: false,
};

// Hardcoded fallbacks in case manifest doesn't exist yet
const FALLBACKS = [
  { id: "DriverProfileCreation", duration: 170, props: { ...DEFAULT_PROPS, title: "CREATE YOUR DRIVER PROFILE", recordingFile: "driversignup.mov", videoSec: 148 } },
  { id: "RideFlow", duration: 139, props: { ...DEFAULT_PROPS, title: "THE RIDE", recordingFile: "ride-flow.mp4", videoSec: 115 } },
];

// Use manifest if available, otherwise fallbacks
const manifestIds = new Set(manifest.map(c => c.id));
const all = [
  ...manifest.map(c => ({ id: c.id, duration: c.duration, props: { ...DEFAULT_PROPS, ...c.props } })),
  ...FALLBACKS.filter(f => !manifestIds.has(f.id)),
];

// REMOTION_COMPOSITION env var controls which composition loads first in Studio.
const preferred = process.env.REMOTION_COMPOSITION;
const sorted = preferred
  ? [...all].sort((a, b) => (a.id === preferred ? -1 : b.id === preferred ? 1 : 0))
  : all;

export const RemotionRoot: React.FC = () => {
  return (
    <>
      {sorted.map((comp) => (
        <Composition
          key={comp.id}
          id={comp.id}
          component={RideFlow}
          durationInFrames={comp.duration * FPS}
          fps={FPS}
          width={VERTICAL_WIDTH}
          height={VERTICAL_HEIGHT}
          defaultProps={comp.props}
        />
      ))}
    </>
  );
};
