#!/usr/bin/env bash
# Bulk-rotate Cloudflare Worker secrets for the prod `hmu-atl` worker.
# Usage:
#   1. Fill in .dev.vars.rotation.tmp with new values (template generated by
#      scripts/rotate-prod-secrets.sh template > .dev.vars.rotation.tmp)
#   2. Run: ./scripts/rotate-prod-secrets.sh
# The rotation file is deleted automatically when the script exits, even on
# error or Ctrl-C — so you cannot forget to clean it up.
set -euo pipefail

FILE=".dev.vars.rotation.tmp"
WRANGLER_CONFIG="wrangler.worker.jsonc"

# Optional: print a template to stdout for the founder to fill in.
if [[ "${1:-}" == "template" ]]; then
  cat <<'EOF'
# Fill each REPLACE_ME with the rotated value, then save and run:
#   ./scripts/rotate-prod-secrets.sh
# This file is auto-deleted by the script and gitignored regardless.

CLERK_SECRET_KEY=REPLACE_ME
CLERK_WEBHOOK_SECRET=REPLACE_ME
DATABASE_URL=REPLACE_ME
DATABASE_URL_UNPOOLED=REPLACE_ME

# Optional — include only if you're rotating these in the same window:
# ABLY_API_KEY=REPLACE_ME
# META_CONVERSIONS_API_TOKEN=REPLACE_ME
EOF
  exit 0
fi

if [[ ! -f "$FILE" ]]; then
  echo "ERROR: $FILE not found." >&2
  echo "Generate a template with: ./scripts/rotate-prod-secrets.sh template > $FILE" >&2
  exit 1
fi

# Refuse to proceed if any *uncommented* value is still REPLACE_ME — guards
# against accidentally setting prod secrets to the literal string 'REPLACE_ME'.
# The `^[^#]*` prefix excludes commented-out template lines.
if grep -E '^[^#]*=REPLACE_ME\s*$' "$FILE" > /dev/null; then
  echo "ERROR: $FILE still has REPLACE_ME values on uncommented lines. Fill them in." >&2
  exit 1
fi

# Always delete the file when the script exits, even on Ctrl-C / failure.
cleanup() {
  if [[ -f "$FILE" ]]; then
    rm -f "$FILE"
    echo "✓ Rotation file deleted."
  fi
}
trap cleanup EXIT INT TERM

echo "→ Pushing rotated secrets to prod worker (hmu-atl)..."
npx wrangler secret bulk "$FILE" --config "$WRANGLER_CONFIG"

echo ""
echo "→ Quick prod health check..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://atl.hmucashride.com/")
if [[ "$HTTP_CODE" == "200" ]]; then
  echo "✓ Prod responded HTTP 200"
else
  echo "⚠ Prod returned HTTP $HTTP_CODE — check logs: wrangler tail hmu-atl"
fi

echo ""
echo "Next:"
echo "  1. Verify auth + DB-using flows still work"
echo "  2. Revoke OLD Clerk keys in Clerk dashboard"
echo "  3. Turn maintenance mode OFF in /admin/maintenance"
