// Funnel CMS — Zone Registry
// Defines every editable content zone across all 5 marketing pages.
// defaultContent holds the current hardcoded value, used for seeding and as fallback.

import type { ZoneRegistryEntry } from './types';

export const ZONE_REGISTRY: ZoneRegistryEntry[] = [
  // ═══════════════════════════════════════════════════════════════
  // DRIVER LANDING PAGE
  // ═══════════════════════════════════════════════════════════════

  // Ticker
  {
    pageSlug: 'driver_landing',
    zoneKey: 'ticker_items',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'json',
    constraints: {},
    displayName: 'Ticker Items',
    description: 'Scrolling ticker bar items at top of driver landing page',
    sortOrder: 1,
    defaultContent: [
      'You set the price',
      'The less you make — the less we take',
      'Hit your cap — we take zero',
      'Cash App • Venmo • Zelle • Bank — always free',
      'Payment secured upfront',
      'No show — still paid',
    ],
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'ticker_speed',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 4 },
    displayName: 'Ticker Speed (seconds)',
    description: 'Animation duration in seconds — lower = faster (default 18)',
    sortOrder: 1,
    defaultContent: '18',
  },

  // Hero
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_eyebrow',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Hero Eyebrow',
    description: 'Small text above hero headline',
    sortOrder: 2,
    defaultContent: 'For ATL Driver-Preneurs',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_headline_line1',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Hero Headline Line 1',
    description: 'First line of hero headline (green)',
    sortOrder: 3,
    defaultContent: 'Keep More.',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_headline_line2',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Hero Headline Line 2',
    description: 'Second line of hero headline',
    sortOrder: 4,
    defaultContent: 'RideFair > Rideshare',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_subheadline',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'rich_text',
    constraints: { maxChars: 200 },
    displayName: 'Hero Subheadline',
    description: 'Supporting text below hero headline',
    sortOrder: 5,
    defaultContent: 'You Drive. You Thrive. Stop Letting Algorithms Determine Your Worth. <strong>Your Pay. Your Way.</strong> HMU.',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_cta_primary',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Hero Primary CTA',
    description: 'Primary button text in hero',
    sortOrder: 6,
    defaultContent: 'Keep More $$$ From My Rides',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_cta_secondary',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Hero Secondary CTA',
    description: 'Ghost button text in hero',
    sortOrder: 7,
    defaultContent: 'See how it works ↓',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'hero_trust_text',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'rich_text',
    constraints: { maxChars: 100 },
    displayName: 'Hero Trust Text',
    description: 'Small trust indicator below CTAs',
    sortOrder: 8,
    defaultContent: 'Drivers live in ATL right now — <strong>try it free today</strong>',
  },

  // Pain Section
  {
    pageSlug: 'driver_landing',
    zoneKey: 'pain_label',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Pain Section Label',
    description: 'Small label above pain headline',
    sortOrder: 10,
    defaultContent: 'The Problem',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'pain_headline',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Pain Headline',
    description: 'Main pain section headline',
    sortOrder: 11,
    defaultContent: 'Other Apps Playin in Our Face',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'pain_body',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 300 },
    displayName: 'Pain Body Text',
    description: 'Supporting paragraph under pain headline',
    sortOrder: 12,
    defaultContent: "You're putting miles on your car, burning gas, blocking time — and they set your rate, take their cut no matter what, and leave you waiting when riders waste your time.",
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'pain_cards',
    audience: 'driver',
    funnelStage: 'awareness',
    zoneType: 'json',
    constraints: {},
    displayName: 'Pain Point Cards',
    description: '3 pain point cards with icon, title, body',
    sortOrder: 13,
    defaultContent: [
      {
        icon: '⏱',
        title: 'They set your price. You just drive.',
        body: "Uber, Lyft — they calculate what you make. Same flat cut whether you did 1 ride or 20. That's not a business, that's a job with worse hours.",
      },
      {
        icon: '🚗',
        title: 'You pull up. They not ready.',
        body: 'You drove 12 minutes to get there. Now they "5 more minutes." That\'s gas, time, and another ride you missed while you sat there waiting.',
      },
      {
        icon: '👻',
        title: 'They cancel. You get nothing.',
        body: "They accepted, you drove over, now they ghost. Other platforms give you a small fee — eventually. HMU protects your time from jump.",
      },
    ],
  },

  // How It Works
  {
    pageSlug: 'driver_landing',
    zoneKey: 'how_label',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'How It Works Label',
    description: 'Section label',
    sortOrder: 20,
    defaultContent: 'How It Works',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'how_headline',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'How It Works Headline',
    description: 'Main headline for how it works section',
    sortOrder: 21,
    defaultContent: 'How Driverpreneurs Get Paid',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'how_subheadline',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'How It Works Subheadline',
    description: 'Supporting text',
    sortOrder: 22,
    defaultContent: 'Post your availability. Set your price. Rider pays before you move. Done.',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'how_steps',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'json',
    constraints: {},
    displayName: 'How It Works Steps',
    description: '4 steps with number, title, body',
    sortOrder: 23,
    defaultContent: [
      {
        num: '01',
        title: 'You post your HMU',
        body: "Tell the city you're available. Your area, your time, your minimum price. Riders in your area see your post and your rating.",
      },
      {
        num: '02',
        title: 'Rider taps Pull Up — money locked',
        body: "When a rider confirms, payment is held before you go anywhere. Not a promise. The money is secured the second they say BET.",
      },
      {
        num: '03',
        title: 'You show up. They better show up.',
        body: "You tap HERE when you arrive. If they're not ready in 10 minutes — no-show fee. You still eat.",
      },
      {
        num: '04',
        title: 'End ride. Get your money.',
        body: "Tap End Ride. Rider has 45 minutes to dispute or payment releases automatically to your Cash App, Venmo, Zelle, or bank.",
      },
    ],
  },

  // Payment Protection
  {
    pageSlug: 'driver_landing',
    zoneKey: 'protection_badge',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Protection Badge',
    description: 'Badge text above protection section',
    sortOrder: 30,
    defaultContent: '🔒 Driver Protection',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'protection_headline',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'rich_text',
    constraints: { maxChars: 60 },
    displayName: 'Protection Headline',
    description: 'Payment protection section headline',
    sortOrder: 31,
    defaultContent: 'Make Money<br /><span style="color: var(--green)">Doin Rides</span>',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'protection_body',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'rich_text',
    constraints: { maxChars: 250 },
    displayName: 'Protection Body',
    description: 'Protection section supporting text',
    sortOrder: 32,
    defaultContent: "We <strong>secure the payment upfront</strong> before you ever leave your block. Once you've made it to the pickup, the rider needs a real reason not to pay.",
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'protection_cards',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Protection Situation Cards',
    description: '3 situation cards showing driver gets paid',
    sortOrder: 33,
    defaultContent: [
      { situation: 'Situation 01', headline: 'No Response', result: 'Get Paid' },
      { situation: 'Situation 02', headline: 'Still Getting Dressed', result: 'Still Gettin Paid' },
      { situation: 'Situation 03', headline: 'Wastin Your Time', result: 'Get Paid' },
    ],
  },

  // ETA Tracking
  {
    pageSlug: 'driver_landing',
    zoneKey: 'tracking_label',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Tracking Section Label',
    description: 'Section label for ETA tracking',
    sortOrder: 40,
    defaultContent: 'Live Tracking',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'tracking_headline',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Tracking Headline',
    description: 'ETA tracking section headline',
    sortOrder: 41,
    defaultContent: 'Stop Guessing Where To Pull Up',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'tracking_subheadline',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 200 },
    displayName: 'Tracking Subheadline',
    description: 'Supporting text for ETA tracking',
    sortOrder: 42,
    defaultContent: 'See exactly where the rider is. They see exactly where you are. No more "where you at" texts. ETA updates in real-time.',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'tracking_features',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'json',
    constraints: {},
    displayName: 'Tracking Feature Bullets',
    description: '5 feature bullets for ETA tracking section',
    sortOrder: 43,
    defaultContent: [
      { icon: '📍', text: 'Real-time GPS — rider sees you OTW, you see their pin' },
      { icon: '⏱️', text: '10-min no-show timer starts when you tap HERE' },
      { icon: '💬', text: 'In-ride chat — no need to share your phone number' },
      { icon: '💵', text: 'Cash Mode — accept cash rides with ETA tracking. 3 free/month, unlimited with HMU First' },
      { icon: '🔐', text: 'Rider info stays private — you see display name only' },
    ],
  },

  // Progressive Fees
  {
    pageSlug: 'driver_landing',
    zoneKey: 'fees_label',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Fees Section Label',
    description: 'Section label for fee section',
    sortOrder: 50,
    defaultContent: 'How We Pay',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'fees_headline',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 80 },
    displayName: 'Fees Headline',
    description: 'Progressive fees section headline',
    sortOrder: 51,
    defaultContent: 'The Less You Make, The Less We Take',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'fees_intro',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'rich_text',
    constraints: { maxChars: 400 },
    displayName: 'Fees Intro Text',
    description: 'Explanation paragraph for progressive fees',
    sortOrder: 52,
    defaultContent: "Other apps take the same flat cut whether you did one ride or ten. <strong>We don't do that.</strong> Your first $50 every day, we only take 10%. The more you earn, the more we earn — but we never go above 25%. And once you hit your daily cap, <strong>we take zero for the rest of the day.</strong>",
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'fee_tiers',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Fee Tier Bars',
    description: '4 progressive fee tier bars',
    sortOrder: 53,
    defaultContent: [
      { label: 'First $50 today', rate: 'We take 10%', keep: 'You keep 90%', width: '90%' },
      { label: '$50–$150 today', rate: 'We take 15%', keep: 'You keep 85%', width: '85%' },
      { label: '$150–$300 today', rate: 'We take 20%', keep: 'You keep 80%', width: '80%' },
      { label: 'Over $300 today', rate: 'We take 25%', keep: 'You keep 75%', width: '75%' },
    ],
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'cap_card',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Daily Cap Card',
    description: 'Daily/weekly cap callout card',
    sortOrder: 54,
    defaultContent: {
      title: 'Daily Cap: $40 max. Weekly Cap: $150 max.',
      body: "No matter how many rides you do, <strong>HMU ATL never takes more than $40 from you in a single day.</strong> Hit your cap and every ride after that is yours — zero platform fee. Resets midnight ET every day. Weekly cap resets every Sunday.",
    },
  },

  // Tier Comparison
  {
    pageSlug: 'driver_landing',
    zoneKey: 'tier_free',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Free Tier Card',
    description: 'Free tier features list',
    sortOrder: 60,
    defaultContent: {
      name: 'Free',
      desc: 'Start earning with zero upfront cost',
      features: [
        'Progressive rate — starts at 10%, first $50/day',
        'Daily cap: $40 max platform fee',
        'Weekly cap: $150 max platform fee',
        'Set your own price',
        'Payment secured upfront',
        'No-show protection',
        'Payout next morning (6am batch)',
        '3 cash rides/month included',
      ],
      lockedFeatures: [
        'Priority placement in driver feed',
        'Instant payouts',
        'Read rider comments',
        'Unlimited cash rides',
      ],
    },
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'tier_hmu_first',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'HMU First Tier Card',
    description: 'HMU First paid tier features',
    sortOrder: 61,
    defaultContent: {
      badge: 'HMU First',
      price: '$9.99',
      priceSub: '/mo',
      desc: 'Flat 12% — lower cap — instant money',
      features: [
        'Flat 12% rate on every ride — never more',
        'Daily cap: $25 max platform fee (lower)',
        'Weekly cap: $100 max platform fee (lower)',
        'Instant payout the second ride ends',
        'Priority placement — shown first to riders',
        'Read what riders said about you',
        'HMU First badge on your profile',
        'Unlimited cash rides — no counter, no packs needed',
      ],
      savingsCallout: '3 rides/day at $20? HMU First pays for itself and you pocket ~$180 more per month vs free.',
    },
  },

  // Payout Methods
  {
    pageSlug: 'driver_landing',
    zoneKey: 'payout_label',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Payout Section Label',
    description: 'Section label for payout methods',
    sortOrder: 70,
    defaultContent: 'How You Get Paid',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'payout_headline',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Payout Headline',
    description: 'Payout methods section headline',
    sortOrder: 71,
    defaultContent: 'Your Money, Your Way',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'payout_subheadline',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 200 },
    displayName: 'Payout Subheadline',
    description: 'Supporting text for payout section',
    sortOrder: 72,
    defaultContent: 'Pick how you want to get paid when you sign up. Switch anytime. Cash App, Venmo, Zelle, and bank transfers are always free.',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'payout_methods',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Payout Methods',
    description: '6 payout method cards',
    sortOrder: 73,
    defaultContent: [
      { icon: '💸', name: 'Cash App', speed: 'Instant • Most popular in ATL', fee: 'FREE', best: true, bestTag: 'Most popular' },
      { icon: '💙', name: 'Venmo', speed: 'Instant', fee: 'FREE', best: true },
      { icon: '🏦', name: 'Zelle', speed: 'Instant bank transfer', fee: 'FREE', best: true },
      { icon: '🏧', name: 'Bank Account', speed: 'Next morning (Free tier) or instant (HMU First)', fee: 'FREE', best: true },
      { icon: '💳', name: 'Debit Card', speed: 'Instant push to any Visa/Mastercard debit', fee: '0.5% fee', note: '~$0.10 on $20' },
      { icon: '🅿️', name: 'PayPal', speed: 'Instant', fee: '1% fee', note: '~$0.20 on $20' },
    ],
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'payout_apple_note',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'rich_text',
    constraints: { maxChars: 300 },
    displayName: 'Apple Pay Payout Note',
    description: 'Note about Apple Pay not supporting payouts',
    sortOrder: 74,
    defaultContent: "<strong>Apple Pay note:</strong> Apple Pay is a spending tool — Apple doesn't allow anyone to receive payouts to it. Use Cash App or Venmo instead and get paid just as fast, for free.",
  },

  // Social Proof
  {
    pageSlug: 'driver_landing',
    zoneKey: 'social_proof_pills',
    audience: 'driver',
    funnelStage: 'evangelism',
    zoneType: 'json',
    constraints: {},
    displayName: 'Social Proof Marquee',
    description: 'Scrolling testimonial pills',
    sortOrder: 80,
    defaultContent: [
      { emoji: '💰', quote: 'First $50 I only paid $4 in fees — wild', author: 'ATL Driver' },
      { emoji: '🔒', quote: 'Cap hit on a Saturday — free rides rest of the day', author: 'Decatur' },
      { emoji: '💸', quote: 'Cash App instant every time', author: 'Bankhead Driver' },
      { emoji: '⏱', quote: 'No more waiting for cancel fees', author: 'East ATL' },
      { emoji: '🚗', quote: 'They not ready? Still paid', author: 'Midtown' },
      { emoji: '⭐', quote: '92% Chill rating after 40 rides', author: 'OG Driver' },
    ],
  },

  // Final CTA
  {
    pageSlug: 'driver_landing',
    zoneKey: 'cta_eyebrow',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Final CTA Eyebrow',
    description: 'Small text above final CTA',
    sortOrder: 90,
    defaultContent: 'Ready to Run It?',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'cta_headline',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Final CTA Headline',
    description: 'Final CTA section headline',
    sortOrder: 91,
    defaultContent: 'Start Earning More Per Ride',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'cta_subheadline',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'Final CTA Subheadline',
    description: 'Supporting text for final CTA',
    sortOrder: 92,
    defaultContent: 'No subscription required to start. Sign up, set your price, post your first HMU.',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'cta_button_text',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Final CTA Button',
    description: 'Submit button text on final CTA form',
    sortOrder: 93,
    defaultContent: 'Keep More $$$ From My Rides',
  },
  {
    pageSlug: 'driver_landing',
    zoneKey: 'cta_fine_print',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 80 },
    displayName: 'Final CTA Fine Print',
    description: 'Small text under submit button',
    sortOrder: 94,
    defaultContent: 'Free to start. No credit card. Cancel anytime.',
  },

  // Offer Details
  {
    pageSlug: 'driver_landing',
    zoneKey: 'offer_details',
    audience: 'driver',
    funnelStage: 'consideration',
    zoneType: 'rich_text',
    constraints: { maxChars: 600 },
    displayName: 'Offer Details / Fee Disclosure',
    description: 'Fee structure disclosure at bottom of page',
    sortOrder: 95,
    defaultContent: '<p><strong>Progressive fees:</strong> The less you make, the less we take. Platform fees range from 10–25% based on your daily earnings, with daily ($40) and weekly ($150) caps.</p><p>Drivers on <strong>HMU First ($9.99/mo)</strong> pay a flat 12% with lower caps ($25/day, $100/week) plus instant payouts after every ride.</p><p>Standard payment processing applies to all transactions. Payouts via Cash App, Venmo, Zelle, and bank are always free.</p>',
  },

  // Nav CTA
  {
    pageSlug: 'driver_landing',
    zoneKey: 'nav_cta_text',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Nav CTA Button',
    description: 'Top nav call-to-action button text',
    sortOrder: 0,
    defaultContent: 'Make More Driving',
  },

  // ═══════════════════════════════════════════════════════════════
  // RIDER LANDING PAGE
  // ═══════════════════════════════════════════════════════════════

  // Ticker
  {
    pageSlug: 'rider_landing',
    zoneKey: 'ticker_items',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'json',
    constraints: {},
    displayName: 'Ticker Items',
    description: 'Scrolling ticker bar items',
    sortOrder: 1,
    defaultContent: [
      'Skip the Surge',
      'Save Up to 60%',
      'Escrow Protected',
      'No Corporate Middleman',
      'Real ATL Drivers',
    ],
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'ticker_speed',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 4 },
    displayName: 'Ticker Speed (seconds)',
    description: 'Animation duration in seconds — lower = faster (default 22)',
    sortOrder: 1,
    defaultContent: '22',
  },

  // Hero
  {
    pageSlug: 'rider_landing',
    zoneKey: 'hero_eyebrow',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Hero Eyebrow',
    description: 'Small text above hero headline',
    sortOrder: 2,
    defaultContent: 'Peer-to-Peer Rides • Metro Atlanta',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'hero_headline_line1',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Hero Headline Line 1',
    description: 'First line of hero headline',
    sortOrder: 3,
    defaultContent: 'STOP PAYING',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'hero_headline_line2',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Hero Headline Line 2',
    description: 'Second line (green)',
    sortOrder: 4,
    defaultContent: 'SURGE PRICES.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'hero_subheadline',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'rich_text',
    constraints: { maxChars: 200 },
    displayName: 'Hero Subheadline',
    description: 'Supporting text below headline',
    sortOrder: 5,
    defaultContent: 'HMU connects you directly with local Atlanta drivers. <strong>Fair prices. Secured payments.</strong> No corporate cut inflating your fare.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'hero_cta_primary',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Hero Primary CTA',
    description: 'Main CTA button text',
    sortOrder: 6,
    defaultContent: 'SIGN UP FREE',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'hero_trust_text',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'rich_text',
    constraints: { maxChars: 100 },
    displayName: 'Hero Trust Text',
    description: 'Trust indicator below CTAs',
    sortOrder: 8,
    defaultContent: 'Drivers live in ATL right now — <strong>rides starting at $5</strong>',
  },

  // Pain
  {
    pageSlug: 'rider_landing',
    zoneKey: 'pain_headline',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Pain Headline',
    description: 'Main pain section headline',
    sortOrder: 11,
    defaultContent: 'TIRED OF THIS?',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'pain_cards',
    audience: 'rider',
    funnelStage: 'awareness',
    zoneType: 'json',
    constraints: {},
    displayName: 'Pain Cards',
    description: '3 rider pain point cards',
    sortOrder: 13,
    defaultContent: [
      { title: '$45 for a 20-minute ride', body: "Uber and Lyft jack up prices whenever they want. Surge pricing at 2am? That's your whole night's budget." },
      { title: 'Random driver every time', body: 'No relationship, no trust. Just a stranger with an app and a rating that means nothing.' },
      { title: 'Money gone before the ride starts', body: 'You get charged immediately. Driver cancels? Good luck getting that refund fast.' },
    ],
  },

  // How It Works
  {
    pageSlug: 'rider_landing',
    zoneKey: 'how_headline',
    audience: 'rider',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'How It Works Headline',
    description: 'Main how it works headline',
    sortOrder: 21,
    defaultContent: 'How HMU Works For Riders',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'how_subheadline',
    audience: 'rider',
    funnelStage: 'interest',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'How It Works Subheadline',
    description: 'Supporting text',
    sortOrder: 22,
    defaultContent: "Post what you need. Pick who you trust. Pay when it's real.",
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'how_steps',
    audience: 'rider',
    funnelStage: 'interest',
    zoneType: 'json',
    constraints: {},
    displayName: 'How It Works Steps',
    description: '4 rider steps',
    sortOrder: 23,
    defaultContent: [
      { num: '01', title: 'Post Your Ride', body: 'Drop your pickup, destination, and what you want to pay. Drivers in your area see it instantly.' },
      { num: '02', title: 'Browse Drivers', body: 'Swipe through available drivers. See their Chill Score, video intro, and reviews from real riders.' },
      { num: '03', title: 'Lock In & Pay', body: "Tap Pull Up to confirm. Your payment is held in escrow — driver doesn't get paid until you arrive safe." },
      { num: '04', title: 'Ride & Rate', body: 'Track your driver in real-time. Rate them after. Build the community you trust.' },
    ],
  },

  // Pricing Comparison
  {
    pageSlug: 'rider_landing',
    zoneKey: 'pricing_headline',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Pricing Headline',
    description: 'Route pricing comparison headline',
    sortOrder: 30,
    defaultContent: 'Real Routes. Real Savings.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'pricing_routes',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Pricing Route Comparisons',
    description: '3 route comparison cards',
    sortOrder: 31,
    defaultContent: [
      { route: 'Buckhead → Airport', hmu: '$18', uber: '$45', save: 'Save 60%' },
      { route: 'Midtown → Downtown', hmu: '$8', uber: '$22', save: 'Save 64%' },
      { route: 'Decatur → Buckhead', hmu: '$15', uber: '$38', save: 'Save 61%' },
    ],
  },

  // Safety & Trust
  {
    pageSlug: 'rider_landing',
    zoneKey: 'safety_headline',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Safety Headline',
    description: 'Trust & safety section headline',
    sortOrder: 40,
    defaultContent: 'Your Safety. Our Priority.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'safety_cards',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Safety Feature Cards',
    description: '4 safety/trust feature cards',
    sortOrder: 41,
    defaultContent: [
      { icon: '🔒', title: 'Escrow Protection', body: 'Your money is held until you arrive. If something goes wrong, you dispute — funds stay locked.' },
      { icon: '✌️', title: 'Chill Score', body: 'Every driver has a community rating. CHILL, Cool AF, or red flags — you see it all before you ride.' },
      { icon: '🎥', title: 'Video Intros', body: 'See your driver before you book. Real face, real person, no catfishing.' },
      { icon: '⏱', title: '45-Min Dispute Window', body: "After every ride, you have 45 minutes to flag anything. We hold the funds until it's resolved." },
    ],
  },

  // OG Status
  {
    pageSlug: 'rider_landing',
    zoneKey: 'og_title',
    audience: 'rider',
    funnelStage: 'evangelism',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'OG Status Title',
    description: 'OG status section title',
    sortOrder: 50,
    defaultContent: 'BECOME AN OG',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'og_body',
    audience: 'rider',
    funnelStage: 'evangelism',
    zoneType: 'rich_text',
    constraints: { maxChars: 200 },
    displayName: 'OG Status Body',
    description: 'OG status description',
    sortOrder: 51,
    defaultContent: 'Complete <strong>10 rides with zero disputes</strong> and unlock OG status. See driver comments. Get priority matching with top-rated drivers. You earned it.',
  },

  // Payment Methods
  {
    pageSlug: 'rider_landing',
    zoneKey: 'payment_headline',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Payment Headline',
    description: 'Rider payment methods headline',
    sortOrder: 60,
    defaultContent: 'Pay Your Way',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'payment_methods',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Payment Method Cards',
    description: '4 rider payment method cards',
    sortOrder: 61,
    defaultContent: [
      { icon: '', name: 'Apple Pay', badge: 'Supported' },
      { icon: 'G', name: 'Google Pay', badge: 'Supported' },
      { icon: '$', name: 'Cash App Pay', badge: 'Supported' },
      { icon: '💳', name: 'Debit / Credit', badge: 'Supported' },
    ],
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'payment_note',
    audience: 'rider',
    funnelStage: 'consideration',
    zoneType: 'rich_text',
    constraints: { maxChars: 200 },
    displayName: 'Payment Security Note',
    description: 'Note about payment security',
    sortOrder: 62,
    defaultContent: '<strong>Secure payments.</strong> All payments processed through Stripe. Your card info never touches our servers.',
  },

  // Testimonials
  {
    pageSlug: 'rider_landing',
    zoneKey: 'testimonials',
    audience: 'rider',
    funnelStage: 'evangelism',
    zoneType: 'json',
    constraints: {},
    displayName: 'Rider Testimonials',
    description: '6 rider testimonials for marquee',
    sortOrder: 70,
    defaultContent: [
      { quote: 'Saved $24 going to the airport. Never using Uber again.', author: 'Marcus, East Atlanta' },
      { quote: 'My driver was chill af. We actually had a real conversation.', author: 'Keya, Decatur' },
      { quote: 'The escrow thing is genius. I feel safe knowing my money is protected.', author: 'Darius, Buckhead' },
      { quote: "I matched with the same driver three times now. It's like having a homie with a car.", author: 'Nia, Midtown' },
      { quote: '$8 from Midtown to Downtown. Uber wanted $22. Do the math.', author: 'Jaylen, West End' },
      { quote: "Video intros sold me. I knew who was pulling up before they got there.", author: 'Tasha, College Park' },
    ],
  },

  // Final CTA
  {
    pageSlug: 'rider_landing',
    zoneKey: 'cta_eyebrow',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Final CTA Eyebrow',
    description: 'Small text above final CTA',
    sortOrder: 90,
    defaultContent: 'Ready to Save?',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'cta_headline',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Final CTA Headline',
    description: 'Final CTA headline',
    sortOrder: 91,
    defaultContent: 'Skip The Surge. Ride For Less.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'cta_subheadline',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'Final CTA Subheadline',
    description: 'Supporting text for final CTA',
    sortOrder: 92,
    defaultContent: 'Join 500+ riders on the waitlist. Sign up free. No credit card required.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'cta_button_text',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Final CTA Button',
    description: 'Submit button text',
    sortOrder: 93,
    defaultContent: 'LOCK IN',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'cta_fine_print',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 80 },
    displayName: 'Final CTA Fine Print',
    description: 'Small text under button',
    sortOrder: 94,
    defaultContent: 'Free to sign up. No credit card. Cancel anytime.',
  },
  {
    pageSlug: 'rider_landing',
    zoneKey: 'nav_cta_text',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 20 },
    displayName: 'Nav CTA Text',
    description: 'Top nav button text',
    sortOrder: 0,
    defaultContent: 'Lock In',
  },

  // ═══════════════════════════════════════════════════════════════
  // HOMEPAGE
  // ═══════════════════════════════════════════════════════════════

  {
    pageSlug: 'homepage',
    zoneKey: 'hero_badge',
    audience: 'all',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 50 },
    displayName: 'Hero Badge',
    description: 'Pill badge text in hero',
    sortOrder: 1,
    defaultContent: 'Launching Q2 2026 • Metro Atlanta',
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'hero_headline_line1',
    audience: 'all',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Hero Headline Line 1',
    description: 'First line (white)',
    sortOrder: 2,
    defaultContent: 'HATE Blank Trips?',
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'hero_headline_line2',
    audience: 'all',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Hero Headline Line 2',
    description: 'Second line (green)',
    sortOrder: 3,
    defaultContent: "Get Atlanta's UpFront Driver Payment Platform.",
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'hero_subheadline',
    audience: 'all',
    funnelStage: 'awareness',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'Hero Subheadline',
    description: 'Supporting paragraph text',
    sortOrder: 4,
    defaultContent: 'Ride Scammers Hate HMU. They Go Ghost? You Get Paid. You Cancel? They Lose Nothing.',
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'hero_stats',
    audience: 'all',
    funnelStage: 'awareness',
    zoneType: 'json',
    constraints: {},
    displayName: 'Hero Stats',
    description: '3 hero stat counters',
    sortOrder: 5,
    defaultContent: [
      { value: '127+', label: 'Drivers Ready' },
      { value: '$8', label: 'Avg. Ride' },
      { value: '60%', label: 'Savings' },
    ],
  },

  // How It Works
  {
    pageSlug: 'homepage',
    zoneKey: 'how_rider_steps',
    audience: 'rider',
    funnelStage: 'interest',
    zoneType: 'json',
    constraints: {},
    displayName: 'How It Works — Riders',
    description: '3 rider steps on homepage',
    sortOrder: 10,
    defaultContent: [
      { num: '01', title: 'Post Your Ride', body: "Tell us where you're going and your price" },
      { num: '02', title: 'Match With a Driver', body: 'Swipe through available drivers in your area' },
      { num: '03', title: 'Pay & Ride', body: 'Payment held in escrow. Released after safe arrival.' },
    ],
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'how_driver_steps',
    audience: 'driver',
    funnelStage: 'interest',
    zoneType: 'json',
    constraints: {},
    displayName: 'How It Works — Drivers',
    description: '3 driver steps on homepage',
    sortOrder: 11,
    defaultContent: [
      { num: '01', title: 'Go Live', body: 'Post your availability to the feed' },
      { num: '02', title: 'Accept Rides', body: 'Choose the rides that work for you' },
      { num: '03', title: 'Get Paid', body: 'Money secured before you pull up. Keep up to 90%.' },
    ],
  },

  // Why HMU
  {
    pageSlug: 'homepage',
    zoneKey: 'why_cards',
    audience: 'all',
    funnelStage: 'interest',
    zoneType: 'json',
    constraints: {},
    displayName: 'Why HMU Cards',
    description: '4 value proposition cards',
    sortOrder: 20,
    defaultContent: [
      { icon: '📉', title: 'Save Up to 60%', desc: 'No surge pricing. No corporate markup. Just fair rides between neighbors.' },
      { icon: '🔒', title: 'Money Secured First', desc: 'Escrow holds payment before the driver pulls up. No chasing payments.' },
      { icon: '🤝', title: 'Community Trust', desc: 'Chill Score ratings. Video intros. Real people, verified by their neighbors.' },
      { icon: '💸', title: 'Driver Keeps More', desc: 'Drivers keep 88-90% of every ride. Daily fee cap means the rest is all theirs.' },
    ],
  },

  // Pricing Snapshot
  {
    pageSlug: 'homepage',
    zoneKey: 'pricing_routes',
    audience: 'all',
    funnelStage: 'consideration',
    zoneType: 'json',
    constraints: {},
    displayName: 'Pricing Route Snapshot',
    description: '3 route comparison cards on homepage',
    sortOrder: 30,
    defaultContent: [
      { route: 'Buckhead → Airport', hmu: '$18', uber: '$45', save: 'Save $27 (60%)' },
      { route: 'Midtown → Downtown', hmu: '$8', uber: '$22', save: 'Save $14 (64%)' },
      { route: 'Decatur → Buckhead', hmu: '$15', uber: '$38', save: 'Save $23 (61%)' },
    ],
  },

  // City Waitlist
  {
    pageSlug: 'homepage',
    zoneKey: 'waitlist_headline',
    audience: 'all',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 40 },
    displayName: 'Waitlist Headline',
    description: 'City waitlist section headline',
    sortOrder: 40,
    defaultContent: 'NOT IN ATLANTA?',
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'waitlist_subheadline',
    audience: 'all',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 150 },
    displayName: 'Waitlist Subheadline',
    description: 'Waitlist supporting text',
    sortOrder: 41,
    defaultContent: "We're starting in Metro Atlanta, but HMU is coming to more cities. Drop your info and we'll let you know when we launch near you.",
  },

  // Dual CTA
  {
    pageSlug: 'homepage',
    zoneKey: 'driver_cta_banner',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Driver CTA Banner',
    description: 'OG banner text on driver CTA card',
    sortOrder: 50,
    defaultContent: 'FIRST $500 FREE • OG PRICING FOR OG DRIVERS',
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'driver_cta_desc',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'Driver CTA Description',
    description: 'Driver sign-up card description',
    sortOrder: 51,
    defaultContent: 'Set your price. Keep up to 90%. Daily fee cap means more money in your pocket.',
  },
  {
    pageSlug: 'homepage',
    zoneKey: 'rider_cta_desc',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 120 },
    displayName: 'Rider CTA Description',
    description: 'Rider sign-up card description',
    sortOrder: 52,
    defaultContent: 'Skip the surge. Save up to 60% on every ride across Metro Atlanta.',
  },

  // ═══════════════════════════════════════════════════════════════
  // DRIVER GUIDE
  // ═══════════════════════════════════════════════════════════════

  {
    pageSlug: 'driver_guide',
    zoneKey: 'guide_title',
    audience: 'driver',
    funnelStage: 'activation',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Guide Title',
    description: 'Main page title',
    sortOrder: 1,
    defaultContent: 'HOW DRIVERS GET PAID ON HMU',
  },
  {
    pageSlug: 'driver_guide',
    zoneKey: 'guide_intro',
    audience: 'driver',
    funnelStage: 'activation',
    zoneType: 'text',
    constraints: { maxChars: 200 },
    displayName: 'Guide Intro',
    description: 'Intro paragraph under title',
    sortOrder: 2,
    defaultContent: "Welcome to HMU ATL. We're Atlanta-based and built this for Atlanta drivers. Here's how the whole ride works, start to finish.",
  },
  {
    pageSlug: 'driver_guide',
    zoneKey: 'guide_steps',
    audience: 'driver',
    funnelStage: 'activation',
    zoneType: 'step_list',
    constraints: {},
    displayName: 'Driver Guide Steps',
    description: '9 steps with num, title, sub, body, tip, icon, color',
    sortOrder: 3,
    defaultContent: [
      { num: '01', title: 'Promote Your Link', sub: 'Share your personal HMU page', body: 'Every driver gets a unique link — atl.hmucashride.com/d/YourHandle. Drop it in your bio, Facebook groups, group chats, anywhere. Riders tap your link to book directly.', tip: 'Use TikTok or VideoLeap to make a 15-second intro video. Drivers with videos get 3x more bookings.', icon: '🔗', color: '#00E676' },
      { num: '02', title: 'Upload Your Video', sub: 'Show riders who you are', body: 'Record a short intro — who you are, what areas you cover, your vibe. This builds trust before riders even book. No script needed, just be you.', tip: 'Keep it 5-10 seconds. Show your face. Mention your areas.', icon: '🎬', color: '#448AFF' },
      { num: '03', title: 'Rider Books You', sub: 'You get notified instantly', body: 'When a rider taps your link and sends a booking request, you get an SMS and in-app notification. You see their name, pickup area, and the price they agreed to.', tip: 'Turn on notifications so you never miss a booking.', icon: '📲', color: '#FFB300' },
      { num: '04', title: 'Payment Is Confirmed', sub: 'Money held before you drive', body: "When the rider taps Pull Up, their payment is held in escrow. You don't leave the house until their money is locked in. No more ride scammers.", tip: 'The hold amount includes the ride price + any add-on reserve.', icon: '🔒', color: '#00E676' },
      { num: '05', title: 'Tap OTW — Head to Pickup', sub: 'GPS tracking starts', body: "Tap OTW (On The Way) and head to the rider. They can see your live location on the map. When you arrive, tap HERE.", tip: "If rider doesn't show within the wait window, you can pull off and keep a no-show fee.", icon: '🚗', color: '#448AFF' },
      { num: '06', title: 'Rider Confirms — Ride Active', sub: 'Payment captured, ride starts', body: "The rider taps BET (heading to your car). Payment is captured at this moment — not at the end. Your earnings are locked in. Drive safe.", tip: 'This is when HMU deducts the platform fee based on your daily earnings tier.', icon: '✅', color: '#00E676' },
      { num: '07', title: 'Add-Ons During the Ride', sub: 'Extra stops, snacks, extras', body: 'If you offer add-on services (extra stops, wait time, etc), the rider can add them during the ride. Each add-on is confirmed and charged separately from the base fare.', tip: 'Set up your Service Menu in your profile to offer add-ons.', icon: '🛒', color: '#FFB300' },
      { num: '08', title: "End Ride — You're Done", sub: 'Dispute window opens', body: "When you drop off the rider, tap End Ride. A short dispute window opens — the rider has a few minutes to flag any issues. If all clear, your payment is finalized.", tip: 'Both you and the rider rate each other after the ride.', icon: '🏁', color: '#448AFF' },
      { num: '09', title: 'Cash Out Your Earnings', sub: 'Instant or standard payout', body: "Go to Cashout, pick your amount with the slider, choose Instant or Standard payout, and tap Cash Out. HMU First members get free instant payouts. Free tier pays $1 or 1%.", tip: "Your first payout may take 1-2 days while Stripe verifies your account. We'll text you when it's ready.", icon: '💰', color: '#00E676' },
    ],
  },
  {
    pageSlug: 'driver_guide',
    zoneKey: 'guide_cta_text',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Guide CTA Button',
    description: 'CTA button at bottom of guide',
    sortOrder: 4,
    defaultContent: 'Start Driving',
  },
  {
    pageSlug: 'driver_guide',
    zoneKey: 'guide_cta_note',
    audience: 'driver',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 80 },
    displayName: 'Guide CTA Note',
    description: 'Small text under CTA button',
    sortOrder: 5,
    defaultContent: "Questions? We're real people in Atlanta. Text us anytime.",
  },

  // ═══════════════════════════════════════════════════════════════
  // RIDER GUIDE
  // ═══════════════════════════════════════════════════════════════

  {
    pageSlug: 'rider_guide',
    zoneKey: 'guide_title',
    audience: 'rider',
    funnelStage: 'activation',
    zoneType: 'text',
    constraints: { maxChars: 60 },
    displayName: 'Guide Title',
    description: 'Main page title',
    sortOrder: 1,
    defaultContent: 'HOW RIDERS BOOK ON HMU',
  },
  {
    pageSlug: 'rider_guide',
    zoneKey: 'guide_intro',
    audience: 'rider',
    funnelStage: 'activation',
    zoneType: 'text',
    constraints: { maxChars: 200 },
    displayName: 'Guide Intro',
    description: 'Intro paragraph',
    sortOrder: 2,
    defaultContent: "Welcome to HMU ATL. We're Atlanta-based and built this for riders tired of surge pricing and ride scammers. Here's how it works.",
  },
  {
    pageSlug: 'rider_guide',
    zoneKey: 'guide_steps',
    audience: 'rider',
    funnelStage: 'activation',
    zoneType: 'step_list',
    constraints: {},
    displayName: 'Rider Guide Steps',
    description: '8 steps with num, title, sub, body, tip, icon, color',
    sortOrder: 3,
    defaultContent: [
      { num: '01', title: 'Find a Driver', sub: 'Browse local ATL drivers', body: 'Open the app and browse drivers in your area. Each driver has a profile with their video intro, areas they serve, pricing, ratings, and chill score. Pick someone you trust.', tip: 'Drivers with videos and high chill scores are verified and trusted by other riders.', icon: '🔍', color: '#00E676' },
      { num: '02', title: 'Book Your Ride', sub: 'Tap their link or request from the feed', body: "Tap a driver's profile to book directly, or post a ride request to the feed and let drivers come to you. You set the price or accept theirs — no surge, no algorithms.", tip: 'Drivers shared their link on social media? Tap it to book them directly.', icon: '📱', color: '#448AFF' },
      { num: '03', title: 'Confirm Payment — Tap Pull Up', sub: 'Your payment is held safely', body: "When you're ready, tap Pull Up. Your payment is held in escrow — the driver sees the hold and knows you're real. They won't drive until your money is locked in.", tip: "You're NOT charged yet — the money is held and only captured when the ride starts. If the driver cancels, you get a full refund.", icon: '🔒', color: '#FFB300' },
      { num: '04', title: 'Share Your Location', sub: 'Driver heads your way', body: 'Share your pickup location or type in an address. The driver taps OTW (On The Way) and you can track them on the map in real-time.', tip: 'Be ready when they arrive — drivers have a wait window. After that they can pull off.', icon: '📍', color: '#00E676' },
      { num: '05', title: 'Driver Arrives — Tap BET', sub: 'Payment captured, ride starts', body: "The driver taps HERE when they arrive. Head to the car and tap BET (I'm coming). This confirms the ride and your payment is captured. You're on your way.", tip: "If you can't make it out in time, communicate through the in-app chat.", icon: '🚗', color: '#448AFF' },
      { num: '06', title: 'Add Extras During the Ride', sub: 'Extra stops, snacks, and more', body: "Need to make a stop? Your driver may offer add-on services like extra stops, wait time, or other extras. You can add them during the ride — each one is priced upfront.", tip: "Add-ons are confirmed by you before they're charged. No surprises.", icon: '🛒', color: '#FFB300' },
      { num: '07', title: 'Ride Complete', sub: 'Rate your driver', body: 'When you arrive, the driver taps End Ride. You have a short window to flag any issues. If everything was cool, the payment is finalized and you rate your driver.', tip: 'Rate honestly — CHILL and Cool AF help drivers earn trust. WEIRDO flags protect the community.', icon: '⭐', color: '#00E676' },
      { num: '08', title: "That's It — No Hidden Fees", sub: 'What you agreed to is what you pay', body: "No surge pricing. No mysterious fees after the ride. The price you agreed to is exactly what you pay. Drivers set fair prices because they keep most of it.", tip: 'Complete 10 rides with 0 disputes and you earn OG status — unlock driver comments and priority matching.', icon: '💯', color: '#448AFF' },
    ],
  },
  {
    pageSlug: 'rider_guide',
    zoneKey: 'guide_cta_text',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 30 },
    displayName: 'Guide CTA Button',
    description: 'CTA button text',
    sortOrder: 4,
    defaultContent: 'Find a Driver',
  },
  {
    pageSlug: 'rider_guide',
    zoneKey: 'guide_cta_note',
    audience: 'rider',
    funnelStage: 'conversion',
    zoneType: 'text',
    constraints: { maxChars: 80 },
    displayName: 'Guide CTA Note',
    description: 'Small text under CTA',
    sortOrder: 5,
    defaultContent: "Questions? We're real people in Atlanta. Text us anytime.",
  },
];

// Helper: get all zones for a page
export function getZonesForPage(pageSlug: string): ZoneRegistryEntry[] {
  return ZONE_REGISTRY.filter((z) => z.pageSlug === pageSlug);
}

// Helper: get default content map for a page
export function getDefaultContentMap(pageSlug: string): Record<string, unknown> {
  const map: Record<string, unknown> = {};
  for (const zone of ZONE_REGISTRY) {
    if (zone.pageSlug === pageSlug) {
      map[zone.zoneKey] = zone.defaultContent;
    }
  }
  return map;
}

// All page slugs
export const PAGE_SLUGS = [
  { slug: 'homepage', label: 'Homepage', path: '/' },
  { slug: 'driver_landing', label: 'Driver Landing', path: '/driver' },
  { slug: 'rider_landing', label: 'Rider Landing', path: '/rider' },
  { slug: 'driver_guide', label: 'Driver Guide', path: '/guide/driver' },
  { slug: 'rider_guide', label: 'Rider Guide', path: '/guide/rider' },
] as const;
